%macro printchr 2
mov ecx,%2
%%abc: pusha
       mov eax,4
       mov ebx,0
       mov ecx,%1
       mov edx,1
       int 80h
       popa
       loop %%abc
%%return: 

%endmacro



%macro printstr 2
mov ecx,%2

      pusha
      mov eax,4
      mov ebx,0
      mov edx,ecx
      mov ecx,%1
     
      int 80h
      popa
     

%endmacro



%macro printint 1

   mov eax,4
   mov ebx,0
   mov ecx,%1
   mov edx,1
   int 80h
%endmacro


